/* eslint-disable no-dupe-keys */
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  //Home
  EventCatWrapper: {
    display: 'flex',
    flexDirection: 'row',
    gap: 30,
    backgroundColor: 'white',
  },
  EventCatSecondWrapper: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 20,
  },
  EventCatDateWrapper: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
  },
  EventCatDateStyle: {
    fontFamily: 'Poppins-Medium',
    color: '#FF8900',
    fontSize: 20,
  },
  EventCatDotStyle: {
    height: 430,
    width: 5,
    borderRightColor: '#C1C5D080',
    borderLeftWidth: 0,
    borderTopWidth: 0,
    borderBottomWidth: 0,
    borderWidth: 3,
    borderStyle: 'dotted',
  },
  EventCatImageStyle: {
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 40,
  },
  EventCatImg: {
    width: 300,
    height: 450,
  },
  LinearGradientStyle: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
    height: 450,
    width: '100%',
  },
  EventCatTitleWrapper: {
    position: 'absolute',
    top: 250,
    margin: 20,
  },
  EventCatDateTextStyle: {
    color: 'white',
    fontFamily: 'Poppins-Regular',
  },
  EventCatTitleStyle: {
    color: 'white',
    fontFamily: 'Poppins-Medium',
    fontSize: 25,
  },
  EventCatFaWrapper: {
    marginTop: 5,
    backgroundColor: 'red',
    width: 40,
    borderRadius: 10,
    padding: 5,
  },
  EventCatBtnStyle: {
    backgroundColor: '#19a7ce',
    borderRadius: 8,
    marginTop: 10,
    marginBottom: 20,
  },
  EventCatBtnTextStyle: {
    fontFamily: 'Poppins-Regular',
    color: 'white',
  },
  EventCategoriesStyle: {
    width: 120,
    height: 50,
    borderRadius: 20,
    borderWidth: 1,
    borderStyle: 'dotted',
    shadowColor: '#52006A',
    backgroundColor: 'white',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 20,
  },
  EventCategoriesItemStyle: {
    fontFamily: 'Poppins-Medium',
  },
  EventsDataWrapper: {
    position: 'relative',
    marginLeft: 20,
  },
  MainWrapper: {
    width: '100%',
    height: '100%',
    backgroundColor: 'white',
  },
  MainSecondWrapper: {
    backgroundColor: '#19a7ce',
    width: '100%',
  },
  FlatListWrapperStyle: {
    marginLeft: 30,
  },
  FlatListEmptyWrapper: {
    backgroundColor: 'white',
  },
  FlatListEmptyStyle: {
    fontFamily: 'Poppins-Medium',
    fontSize: 20,
    textAlign: 'center',
    marginTop: 20,
  },
  HomeAppbar: {
    fontFamily: 'Poppins-Medium',
    paddingLeft: 70,
  },
  SearchStyle: {
    fontFamily: 'Poppins-Regular',
    color: 'white',
    position: 'absolute',
    top: 7,
    left: 50,
    fontSize: 20,
  },
  MainEventsWrapper: {
    backgroundColor: 'white',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
  },
  HomeMainWrapper: {
    backgroundColor: '#222B45',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
  },
  MainEventsSecondWrapper: {
    display: 'flex',
    flexDirection: 'column',
    gap: 25,
  },
  DiscoverWrapperStyle: {
    marginHorizontal: 20,
  },
  DiscoverTextStyle: {
    fontFamily: 'Poppins-Medium',
    fontSize: 20,
    marginBottom: 20,
  },
  UpcomingStyle: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
  },
  UpcomingTextStyle: {
    fontFamily: 'Poppins-Medium',
    fontSize: 20,
    marginBottom: 20,
  },
  UpcomingBtnStyle: {
    color: '#3366ff',
    fontFamily: 'Poppins-Regular',
  },
  TextInputWrapper: {
    height: 80,
    backgroundColor: '#19A7CE',
    padding: 18,
    zIndex: 0,
  },
  TextInputChildWrapper: {
    position: 'relative',
  },
  IconSearchStyle: {
    position: 'absolute',
    top: 9,
    left: 15,
    color: 'white',
  },
  SearchInput: {
    borderWidth: 1,
    borderColor: 'white',
    fontSize: 18,
    height: 45,
    color: 'white',
    borderRadius: 10,
    paddingLeft: 50,
    fontFamily: 'Poppins-Regular',
    paddingBottom: 4,
  },
  EventsTextStyle: {
    fontSize: 20,
    fontFamily: 'Poppins-Medium',
    paddingTop: 15,
  },
  EventsWrapperStyle: {
    marginHorizontal: 25,
    marginTop: 15,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  HomeDateWrapper: {
    width: '100%',
    height: 100,
    backgroundColor: '#222B45',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
  },
  ListEventWrapper: {
    backgroundColor: 'white',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
  },
  HomeDateStyle: {
    paddingHorizontal: 36,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 40,
    height: '100%',
  },
  HomeDateTextStyle: {
    color: 'white',
    fontFamily: 'Poppins-Medium',
  },
  //Search Results
  LimitDropdownStyle: {
    width: '25%',
    height: 40,
    backgroundColor: '#FFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#19a7ce',
    fontFamily: 'Poppins-Medium',
  },
  LimitBtnTextStyle: {
    color: '#444',
    textAlign: 'left',
    fontFamily: 'Poppins-Medium',
    padding: 6,
  },
  SortBtnStyle: {
    width: '40%',
    height: 40,
    backgroundColor: '#FFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#19a7ce',
    fontFamily: 'Poppins-Medium',
  },
  PageInfoStyle: {
    borderWidth: 1,
    borderRadius: 5,
    padding: 10,
    borderColor: '#19a7ce',
  },
  PageInfoSecondStyle: {
    borderWidth: 1,
    borderRadius: 5,
    padding: 10,
    borderColor: '#19a7ce',
  },
  //Custom Drawer
  CustomDrawerWrapper: {
    flex: 1,
  },
  ProfileImgWrapper: {
    height: 80,
    width: 80,
    borderRadius: 40,
    marginBottom: 10,
  },
  ProfileWrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
    marginHorizontal: 10,
    marginVertical: 50,
  },
  FullNameStyle: {
    fontSize: 18,
    fontFamily: 'Poppins-Medium',
    marginBottom: 5,
  },
  ProfessionWrapper: {
    flexDirection: 'row',
  },
  ProfessionTextStyle: {
    fontFamily: 'Poppins-Regular',
    marginRight: 5,
  },
  DrawerItemWrapper: {
    flex: 1,
    backgroundColor: '#fff',
    paddingTop: 10,
  },
  LogoutBtnStyle: {
    paddingVertical: 15,
  },
  LogoutWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 28,
    marginLeft: 20,
  },
  LogoutTextStyle: {
    fontSize: 13,
    fontFamily: 'Poppins-Medium',
    marginLeft: 5,
    color: 'red',
  },
  //Event Details
  ScrollViewWrapper: {
    position: 'relative',
    backgroundColor: 'white',
  },
  DetailImgWrapper: {
    width: '100%',
    height: '0%',
    position: 'relative',
  },
  DetailImgStyle: {
    height: 450,
    width: '100%',
  },
  DetailContentWrapper: {
    position: 'absolute',
    top: 50,
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    paddingHorizontal: 25,
  },
  DetailTextWrapper: {
    position: 'absolute',
    top: 180,
    margin: 20,
  },
  DetailTitleStyle: {
    color: 'white',
    fontFamily: 'Poppins-Medium',
    fontSize: 25,
  },
  DetailLocationWrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  DetailTimeWrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  AttendeeTextStyle: {
    fontFamily: 'Poppins-Regular',
    color: 'white',
    fontSize: 20,
  },
  AttendeeWrapperStyle: {
    display: 'flex',
    flexDirection: 'row',
  },
  AttendeeStyle: {
    overflow: 'hidden',
    borderRadius: 100,
    width: 40,
  },
  AttendeeImgStyle: {
    width: 40,
    height: 40,
  },
  EventDetailStyle: {
    padding: 30,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    backgroundColor: 'white',
    top: 420,
  },
  EventDetailTextStyle: {
    fontFamily: 'Poppins-Medium',
    fontSize: 20,
    color: 'black',
  },
  ReadMoreStyle: {
    fontFamily: 'Poppins-Regular',
    color: '#3366ff',
    fontSize: 13,
  },
  LocationTextStyle: {
    fontFamily: 'Poppins-Medium',
    fontSize: 20,
    color: 'black',
    marginTop: 10,
  },
  BuyBtnStyle: {
    backgroundColor: '#19a7ce',
    borderRadius: 8,
    padding: 8,
  },
  BuyBtnTextStyle: {
    color: 'white',
    fontFamily: 'Poppins-Medium',
    textAlign: 'center',
    padding: 5,
  },
  BuyTicketWrapper: {
    marginTop: 30,
  },
  //Sign In
  ScrollViewStyle: {
    backgroundColor: '#19a7ce',
  },
  HomeHeaderStyle: {
    backgroundColor: '#19A7CE',
  },
  ViewHeader: {
    display: 'flex',
    flexDirection: 'column',
    gap: 5,
    padding: 50,
  },
  TextLoginStyle: {
    fontSize: 24,
    color: 'black',
    fontFamily: 'Poppins-Medium',
  },
  SubtitleWrapper: {
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
  },
  FormErrorViewStyle: {
    paddingLeft: 50,
    paddingRight: 50,
  },
  FormErrorTextStyle: {
    backgroundColor: '#e23258',
    padding: 10,
    color: 'white',
    borderRadius: 10,
    marginBottom: 30,
    fontFamily: 'Poppins-Medium',
  },
  FormSuccessTextStyle: {
    backgroundColor: '#19a7ce',
    padding: 10,
    color: 'white',
    borderRadius: 10,
    marginBottom: 30,
    fontFamily: 'Poppins-Medium',
  },
  FormWrapperStyle: {
    display: 'flex',
    flexDirection: 'column',
    gap: 30,
    paddingLeft: 50,
    paddingRight: 50,
  },
  FormTextInputErrorStyle: {
    borderWidth: 1,
    borderColor: 'red',
    borderRadius: 15,
    borderStyle: 'solid',
    paddingLeft: 20,
    fontFamily: 'Poppins-Regular',
    paddingTop: 15,
    paddingLeft: 20,
  },
  FormTextInputNormalStyle: {
    borderWidth: 1,
    borderColor: '#C1C5D0',
    borderRadius: 15,
    borderStyle: 'solid',
    paddingLeft: 20,
    fontFamily: 'Poppins-Regular',
    paddingTop: 15,
    paddingLeft: 20,
  },
  FormTextErrorStyle: {
    color: 'red',
    paddingTop: 10,
    fontFamily: 'Poppins-Regular',
  },
  PasswordWrapperStyle: {
    position: 'relative',
  },
  EyeButtonStyle: {
    position: 'absolute',
    top: 12,
    right: 15,
  },
  ForgotPasswordWrapperStyle: {
    marginLeft: 50,
    marginRight: 50,
  },
  ForgotPassTextStyle: {
    color: '#3366FF',
    paddingTop: 15,
    textAlign: 'right',
    fontFamily: 'Poppins-Regular',
  },
  BtnWrapperStyle: {
    paddingLeft: 40,
    paddingRight: 40,
    paddingTop: 30,
  },
  FontStyle: {
    fontFamily: 'Poppins-Regular',
  },
  AlternateSignWrapper: {
    display: 'flex',
    marginTop: 50,
    marginLeft: 40,
    marginRight: 40,
    marginBottom: 40,
    flexDirection: 'column',
    gap: 20,
  },
  AlternateSignSecondWrapper: {
    paddingLeft: '50',
    paddingRight: '50',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  LogoWrapperStyle: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  LogoBorderStyle: {
    borderWidth: 2,
    width: 95,
    height: 52,
    borderColor: '#3366FF',
    borderRadius: 6,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  //Create Event
  CreateEventWrapper: {
    width: '100%',
    height: '100%',
    backgroundColor: '#19a7ce',
  },
  CreateEventAppbar: {
    fontFamily: 'Poppins-Medium',
    paddingLeft: 70,
    color: 'white',
  },
  ContentWrapperStyle: {
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    backgroundColor: 'white',
  },
  InputEventStyle: {
    fontFamily: 'Poppins-Medium',
    marginBottom: 5,
  },
  CategoryTextStyle: {
    fontFamily: 'Poppins-Medium',
    marginBottom: 5,
    marginTop: 5,
  },
  CategoriesDropdown: {
    textAlign: 'left',
    fontFamily: 'Poppins-Medium',
    color: 'gray',
    fontSize: 16,
    paddingTop: 3,
  },
  DropdownRowStyle: {
    backgroundColor: '#EFEFEF',
    borderBottomColor: '#C5C5C5',
  },
  DropdownStyle: {
    backgroundColor: '#EFEFEF',
  },
  DropdownRowTextStyle: {
    color: '#444',
    textAlign: 'left',
    fontFamily: 'Poppins-Regular',
  },
  CreateEventForm: {
    padding: 30,
  },
  DateTextStyle: {
    fontFamily: 'Poppins-Medium',
    marginTop: 6,
  },
  DateWrapperStyle: {
    borderWidth: 1,
    height: 50,
    borderColor: '#9DB2BF',
    borderRadius: 5,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    paddingVertical: 12,
  },
  PoppinsMedium: {
    fontFamily: 'Poppins-Medium',
  },
  SelectPictureText: {
    fontFamily: 'Poppins-Medium',
    marginTop: 6,
  },
  DescriptionStyle: {
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#9DB2BF',
    paddingLeft: 10,
    width: '100%',
    height: 200,
  },
  PoppinsRegular: {
    fontFamily: 'Poppins-Regular',
  },
  CreateEventBtnStyle: {
    marginTop: 10,
  },
  ModalStyle: {
    width: '100%',
    height: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 25,
    backgroundColor: 'white',
  },
  EditPictureImg: {
    width: 100,
    height: 150,
  },
  //Sign Up
  LinkLoginStyle: {
    color: 'blue',
    fontFamily: 'Poppins-Regular',
  },
  TermsWrapper: {
    display: 'flex',
    flexDirection: 'row',
    paddingLeft: 40,
    paddingTop: 10,
    alignItems: 'center',
  },
  TermsText: {
    fontFamily: 'Poppins-Regular',
    paddingTop: 3,
  },
  //Change Password
  ChangePasswordWrapper: {
    width: '100%',
    height: '100%',
  },
  Relative: {
    position: 'relative',
  },
  ChangePasswordSecondWrapper: {
    backgroundColor: 'white',
    borderRadius: 40,
    width: '100%',
    height: '100%',
  },
  ChangePassFormWrapper: {
    paddingTop: 50,
  },
  //My Booking
  BookingWrapper: {
    backgroundColor: 'white',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    paddingTop: 20,
  },
  BookingBtnStyle: {
    backgroundColor: '#19a7ce',
    width: 100,
    margin: 20,
    padding: 10,
    borderRadius: 10,
  },
  BookingCreateStyle: {
    fontFamily: 'Poppins-Medium',
    color: 'white',
    paddingTop: 3,
    textAlign: 'center',
  },
  BookingFlatlistStyle: {
    width: '100%',
    height: '100%',
    backgroundColor: 'white',
  },
  //MyWishlist
  WishlistFlatlist: {
    backgroundColor: 'white',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
  },
  //Manage Event
  AppWrapper: {
    backgroundColor: '#19a7ce',
    width: '100%',
    height: '100%',
  },
  ManageHeaderStyle: {
    textAlign: 'center',
    fontFamily: 'Poppins-Medium',
    color: 'white',
    backgroundColor: '#19a7ce',
    marginRight: 40,
  },
  ManageWrapperStyle: {
    display: 'flex',
    flexDirection: 'row',
    gap: 30,
    paddingTop: 20,
    paddingBottom: 20,
    paddingRight: 40,
    paddingLeft: 40,
  },
  ManageWrapperChildStyle: {
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
  },
  DateWrapper: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: 5,
    borderRadius: 10,
  },
  TextDate: {
    fontFamily: 'Poppins-Bold',
    color: 'orange',
    fontSize: 18,
  },
  HeartWrapper: {
    display: 'flex',
    alignItems: 'center',
  },
  TitleWrapper: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  TitleStyles: {
    fontSize: 24,
    fontFamily: 'Poppins-Medium',
    color: 'black',
  },
  ManageBtn: {
    fontFamily: 'Poppins-Regular',
    color: '#3366ff',
    marginTop: 10,
  },
  CreateBtnStyle: {
    backgroundColor: '#19a7ce',
    width: 100,
    margin: 20,
    padding: 10,
    borderRadius: 10,
  },
  CreateTextStyle: {
    fontFamily: 'Poppins-Medium',
    color: 'white',
    paddingTop: 3,
    textAlign: 'center',
  },
  ManageWrapper: {
    backgroundColor: 'white',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    width: '100%',
    height: '100%',
    paddingTop: 20,
  },
  NoBtnStyle: {
    backgroundColor: 'green',
    width: 80,
    height: 50,
    borderRadius: 12,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  //Payment Method
  PaymentWrapper: {
    width: '100%',
    height: '100%',
    backgroundColor: 'white',
    paddingLeft: 30,
    paddingTop: 30,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
  },
  TextPayment: {
    fontFamily: 'Poppins-Bold',
    fontSize: 20,
    color: 'black',
  },
  PaymentMethodWrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 30,
    justifyContent: 'space-between',
    marginRight: 50,
  },
  PaymentMethodChildWrapper: {
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  PaymentMethodText: {
    fontFamily: 'Poppins-Medium',
    color: 'black',
  },
  PaymentFlatlistStyle: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    height: '80%',
    justifyContent: 'space-between',
  },
  PaymentMethodImg: {
    width: 50,
    height: 50,
  },
  TotalPaymentWrapper: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  TotalPaymentSecondWrapper: {
    display: 'flex',
    flexDirection: 'row',
    gap: 20,
    paddingTop: 30,
  },
  TotalPaymentTextStyle: {
    fontSize: 15,
    fontFamily: 'Poppins-Medium',
    color: 'black',
  },
  MakePaymentBtnStyle: {
    width: 150,
    height: 40,
    backgroundColor: '#19a7ce',
    borderRadius: 5,
    margin: 20,
  },
  MakePaymentTextStyle: {
    fontFamily: 'Poppins-Medium',
    textAlign: 'center',
    paddingTop: 8,
    color: 'white',
  },
  //Profile
  ProfileAppbarContent: {
    fontFamily: 'Poppins-Medium',
    paddingLeft: 115,
    color: 'white',
  },
  ProfileWrapperStyle: {
    backgroundColor: 'white',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    height: '100%',
  },
  ProfileTextStyle: {
    fontFamily: 'Poppins-Medium',
    fontSize: 20,
    textAlign: 'center',
  },
  ProfileProfession: {
    fontFamily: 'Poppins-Medium',
    fontSize: 13,
    textAlign: 'center',
  },
  ProfileCardWrapper: {
    margin: 20,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  PlusBtnStyle: {
    borderWidth: 3,
    padding: 10,
    borderRadius: 5,
    borderStyle: 'dotted',
  },
  CardWrapperStyle: {
    margin: 20,
  },
  EditProfileStyle: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginRight: 30,
  },
  EditProfileWrapper: {
    margin: 20,
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  ChangePasswordStyle: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginRight: 30,
  },
  ChangePasswordText: {
    margin: 20,
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  //Delete Modal Style
  DeleteModalWrapper: {
    width: '100%',
    height: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 25,
    backgroundColor: 'white',
  },
  DeleteModalSecondWrapper: {
    width: '80%',
    height: '20%',
    padding: 10,
    backgroundColor: '#19a7ce',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 20,
    borderRadius: 20,
    opacity: 1,
    elevation: 20,
  },
  DeleteModalTextStyle: {
    fontFamily: 'Poppins-Medium',
    color: 'white',
    textAlign: 'center',
  },
  //Profile
  AppbarProfile: {
    fontFamily: 'Poppins-Medium',
    paddingLeft: 115,
    color: 'white',
  },
  SkeletonHeight: {
    height: 230,
  },
  DocumentSelectWrapper: {
    display: 'flex',
    flexDirection: 'row',
    gap: 20,
  },
  DeleteWrapperStyle: {
    backgroundColor: '#F24C3D',
    width: 80,
    height: 50,
    borderRadius: 12,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  SelectPictureStyle: {
    backgroundColor: '#19a7ce',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    marginTop: 5,
    marginBottom: 50,
  },
  SelectPictureTextStyle: {
    fontFamily: 'Poppins-Regular',
    color: 'white',
    paddingTop: 5,
    paddingHorizontal: 8,
  },
  CameraBtnStyle: {
    backgroundColor: '#19a7ce',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    marginTop: 5,
    marginBottom: 50,
    paddingHorizontal: 20,
  },
  EditGenderTextStyle: {
    fontFamily: 'Poppins-Medium',
    color: '#3366ff',
    marginLeft: 10,
  },
  ProfileDropdownBtn: {
    color: '#444',
    textAlign: 'left',
    fontFamily: 'Poppins-Regular',
  },
  ContentWrapper: {
    width: '100%',
    height: '100%',
    backgroundColor: '#19a7ce',
  },
  PictureWrapper: {
    alignItems: 'center',
    height: 200,
  },
  PictureChildWrapper: {
    overflow: 'hidden',
    width: '50%',
    height: '100%',
    marginTop: 30,
  },
  ImageStyle: {
    objectFit: 'cover',
    width: '80%',
    height: '80%',
    borderRadius: 100,
    marginLeft: 20,
    borderWidth: 3,
    borderColor: '#19a7ce',
  },
  ProfileContentWrapper: {
    margin: 20,
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
  },
  ProfileContentHeader: {
    fontFamily: 'Poppins-Medium',
    fontSize: 18,
  },
  ProfileNameInput: {
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#9DB2BF',
    paddingLeft: 10,
    width: '100%',
    fontFamily: 'Poppins-Medium',
    paddingVertical: 13,
  },
  EditBtnStyle: {
    fontFamily: 'Poppins-Medium',
    color: '#3366ff',
  },
  ProfileValueWrapper: {
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
  },
  GenderWrapperStyle: {
    display: 'flex',
    flexDirection: 'row',
  },
  RadioWrapperStyle: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  SelectDropdownStyle: {
    width: '100%',
    height: 50,
    backgroundColor: '#FFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#9DB2BF',
    fontFamily: 'Poppins-Medium',
  },
  BirthDateWrapper: {
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
  },
  SaveBtnStyle: {
    width: '100%',
    backgroundColor: '#19a7ce',
    padding: 12,
    borderRadius: 10,
  },
  SaveTextStyle: {
    fontFamily: 'Poppins-Medium',
    color: 'white',
    textAlign: 'center',
  },
  //Purchase Ticket
  TicketImgWrapper: {
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 30,
  },
  TicketWrapper: {
    marginHorizontal: 30,
    borderRadius: 10,
  },
  TitleWrapperStyle: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  TicketTitleStyle: {
    fontFamily: 'Poppins-Medium',
    fontSize: 20,
    color: 'black',
    paddingTop: 18,
  },
  FilterWrapperStyle: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  FilterTextStyle: {
    fontFamily: 'Poppins-Bold',
    color: '#FF3D71',
  },
  TicketContentWrapper: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    marginHorizontal: 30,
  },
  TicketSectionWrapper: {
    display: 'flex',
    flexDirection: 'row',
    gap: 70,
  },
  TicketSectionTextStyle: {
    fontFamily: 'Poppins-Bold',
    color: 'black',
  },
  QuantityWrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 100,
    marginLeft: 55,
    marginTop: 10,
  },
  QuantityTextStyle: {
    fontFamily: 'Poppins-Regular',
    color: 'black',
  },
  QuantityBtnWrapper: {
    display: 'flex',
    flexDirection: 'row',
    gap: 20,
    alignItems: 'center',
  },
  QuantityBtn: {
    borderWidth: 2,
    padding: 5,
    borderColor: '#C1C5D0',
    borderRadius: 5,
  },
  ErrorBtnWrapper: {
    marginTop: 50,
  },
  SortStyle: {
    marginHorizontal: 30,
  },
  PoppinsBold: {
    fontFamily: 'Poppins-Bold',
  },
  SeatsStyle: {
    fontFamily: 'Poppins-Regular',
    fontSize: 10,
  },
  PurchaseWrapperStyle: {
    marginBottom: 30,
  },
  CheckoutBtnStyle: {
    fontFamily: 'Poppins-Medium',
    textAlign: 'center',
    paddingTop: 8,
    color: 'white',
  },
  CheckoutStyle: {
    width: 150,
    height: 40,
    backgroundColor: '#19a7ce',
    borderRadius: 5,
    margin: 20,
  },
  SectionTextStyle: {
    fontSize: 15,
    fontFamily: 'Poppins-Medium',
    color: 'black',
  },
  SectionWrapper: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: 'white',
  },
  SectionStyle: {
    display: 'flex',
    flexDirection: 'row',
    gap: 20,
    paddingTop: 30,
    paddingLeft: 20,
  },
});

export default styles;
